require 'serverspec'

include Serverspec::Helper::Exec
include Serverspec::Helper::DetectOS

describe package('collectd-core') do
  it { should be_installed }
end

describe process('collectd') do
  it { should be_running }
end

describe command('collectd -t') do
  # there is bug in exit code for collectd 5.1.0 (always return 0)
  it { should return_stdout '' }
  # in version >= 5.4.0 use exit code
  it { should return_exit_status 0 }
end

describe file('/etc/collectd/plugins/autogenerated.conf') do
  it { should_not be_file }
end

describe file('/etc/collectd/plugins/custom.conf') do
  it { should be_file }
end

describe file('/etc/collectd/plugins/df.conf') do
  it { should be_file }
end
